### ISSUE TITLE
Add unnecessary semicolons on jsx

### ISSUE THREAD

**Issue by gh0stonio** [bulyshko/esformatter-semicolons#8]
Hi,

When the formatter try to format jsx code, it had some semicolons inside the HTML like part.

The issue is explain [here](https://github.com/ricardofbarros/semistandard-format/issues/7) in the semistandard repository.

**Comment by gh0stonio** [comment]
My bad, it seems to be a problem using esformatter-semicolons and esformatter-jsx together.

The jsx formatter add some spaces before and after brackets, so the esformatter-semicolons add semicolons thinking they are missing.

**Comment by millermedeiros** [comment]
more details about the issue here: https://github.com/millermedeiros/esformatter/issues/472

**Comment by bulyshko** [comment]
@gh0stonio Can you please provide the exact input, output, configuration, and package versions. Thanks.

**Comment by ujwal-setlur** [comment]
I see this too. semi-colons are added to javascript expressions inside jsx. Is this intended?

<View someProp={true} />

becomes 

<View someProp={true;} />

**Comment by bulyshko** [comment]
@ujwal-setlur Hi, can you please provide your configuration and package versions? I was not able to reproduce this. Thanks.

**Comment by ujwal-setlur** [comment]
@bulyshko Hi, here is a sample code:

```
import React from "react";;
import Home from "./Home"

class HomeContainer extends React.Component {
  render() {
    return (
      <Home
        aProp={true}
      />
      );
  }
}

export default HomeContainer;
```

You will see the problem if you run it with the esformatter-jsx plugin enabled. You will see a semicolon inserted after **true** in aProp={true}, which should not happen.

esformatter --plugins=esformatter-jsx,esformatter-semicolons semicolonsTest.js

```
import React from "react";
import Home from "./Home";

class HomeContainer extends React.Component {
  render() {
    return (
      <Home aProp={ true; } />
      );
  }
}

export default HomeContainer;
```

If you use only the semicolons plugin, it works fine, but I need my jsx formatted as well so I need to use esformatter-jsx.  

esformatter --plugins=esformatter-semicolons semicolonsTest.js

```
import React from "react";
import Home from "./Home";

class HomeContainer extends React.Component {
  render() {
    return (
      <Home
      aProp={true}
      />
      );
  }
}

export default HomeContainer;
```
